// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/2/2026, 2:31:03 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/mdreesen/Documents/Programming/business-projects/autodash/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mdreesen/Documents/Programming/business-projects/autodash/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mdreesen/Documents/Programming/business-projects/autodash/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mdreesen/Documents/Programming/business-projects/autodash/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mdreesen/Documents/Programming/business-projects/autodash/app/plugins/**/*.{js,ts,mjs}","/Users/mdreesen/Documents/Programming/business-projects/autodash/app/composables/**/*.{js,ts,mjs}","/Users/mdreesen/Documents/Programming/business-projects/autodash/app/utils/**/*.{js,ts,mjs}","/Users/mdreesen/Documents/Programming/business-projects/autodash/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mdreesen/Documents/Programming/business-projects/autodash/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mdreesen/Documents/Programming/business-projects/autodash/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mdreesen/Documents/Programming/business-projects/autodash/app/app.config.{js,ts,mjs}","/Users/mdreesen/Documents/Programming/business-projects/autodash/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;